INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Farrah Petty",218,2,"Palma de Mallorca"),
  ("Adena Barnes",52,2,"Elx"),
  ("Bo Washington",398,1,"Pontevedra"),
  ("Carter Berry",228,2,"Melilla"),
  ("Shad Ray",326,1,"San Cristóbal de la Laguna"),
  ("Martin Noble",401,1,"Teruel"),
  ("Kim Stevenson",254,2,"Melilla"),
  ("Russell Moon",242,1,"Ceuta"),
  ("Fritz Bean",316,1,"Ciudad Real"),
  ("Quemby Sloan",224,1,"Girona"),
  ("Porter Ford",339,2,"Pamplona"),
  ("Pamela Ramsey",411,2,"Santander"),
  ("Zenaida Hernandez",229,2,"Jaén"),
  ("Perry Jackson",314,2,"Badajoz"),
  ("Lionel Bentley",238,2,"Cáceres"),
  ("Stuart Wiley",352,1,"Pamplona"),
  ("Sara Knight",194,2,"Murcia"),
  ("Roary Sharpe",371,2,"Zaragoza"),
  ("Ignacia Kaufman",396,1,"Palma de Mallorca"),
  ("Sasha Alvarez",334,2,"Ceuta");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Tate Payne",244,1,"Madrid"),
  ("Gillian Beach",175,1,"Gijón"),
  ("Ariana Byers",207,2,"Cartagena"),
  ("Yael Foley",337,2,"Las Palmas"),
  ("Nichole Evans",431,1,"Santander"),
  ("Wade Wells",235,1,"Torrevieja"),
  ("Justine Charles",255,1,"Huesca"),
  ("Bert May",171,2,"Cartagena"),
  ("Alfonso Gamble",220,1,"Pamplona"),
  ("Maris Marks",212,2,"Murcia"),
  ("Keefe Simmons",48,1,"Pamplona"),
  ("Shana Howard",160,1,"A Coruña"),
  ("Cora Castro",124,2,"Pontevedra"),
  ("Whitney Cole",152,1,"Logroño"),
  ("Zoe Fleming",438,1,"Vigo"),
  ("Candice Parsons",182,1,"Santander"),
  ("Jaquelyn Moses",84,2,"Cartagena"),
  ("Magee Fulton",195,2,"Ceuta"),
  ("Urielle Page",108,1,"Logroño"),
  ("Paloma Rowland",165,1,"Cartagena");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Nasim Kelley",214,1,"Melilla"),
  ("Eve Vincent",228,1,"Gijón"),
  ("Kennedy Mcdowell",326,1,"Oviedo"),
  ("Gail Palmer",132,1,"Melilla"),
  ("Katell O'Neill",72,2,"Badajoz"),
  ("Noble Rush",51,1,"Elx"),
  ("Raja Horton",425,1,"Palma de Mallorca"),
  ("Tarik Sharp",387,2,"Cartagena"),
  ("Darius Santos",396,2,"Gijón"),
  ("Malachi Barrett",352,2,"San Cristóbal de la Laguna");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Marny Vaughn",192,1,"Pamplona"),
  ("Tyrone Chang",413,1,"L'Hospitalet de Llobregat"),
  ("Jessamine Hopkins",175,1,"Huelva"),
  ("Yvette Nichols",112,1,"Badajoz"),
  ("Carl Briggs",319,1,"Donosti"),
  ("Graham Greer",61,1,"Ciudad Real"),
  ("Deanna Williamson",255,1,"Guadalajara"),
  ("Elizabeth Forbes",308,2,"Ceuta"),
  ("Jordan Vega",292,1,"Gijón"),
  ("Raymond Vaughan",418,1,"Palma de Mallorca"),
  ("Tanner Mccarty",111,2,"Burgos"),
  ("Bo Valentine",447,2,"San Cristóbal de la Laguna"),
  ("Hashim Beach",291,2,"Pamplona"),
  ("Rogan Keller",348,2,"Guadalajara"),
  ("Nola Baldwin",437,1,"Oviedo"),
  ("Burton Carney",338,1,"Logroño"),
  ("Dylan Smith",192,1,"Torrevieja"),
  ("Roary Mccray",127,1,"Donosti"),
  ("Sybil Fry",341,1,"Dos Hermanas"),
  ("Malik Marshall",139,1,"Pamplona");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Alvin Mckenzie",173,2,"Pamplona"),
  ("Steel Mccarty",54,1,"Gijón"),
  ("Dustin Cain",179,2,"Bilbo"),
  ("Vladimir Beasley",327,1,"Donosti"),
  ("Keith Dickson",146,2,"Cáceres"),
  ("Brady Harrison",325,1,"Melilla"),
  ("Kareem Raymond",285,2,"Santander"),
  ("Larissa Keller",169,1,"Barcelona"),
  ("Kane Chen",449,2,"Santa Cruz de Tenerife"),
  ("Germaine Craig",253,1,"Huelva"),
  ("Addison Galloway",329,2,"Alacant"),
  ("Melvin George",30,2,"Gasteiz"),
  ("Colt Mccray",196,1,"Donosti"),
  ("Baker Gallegos",148,2,"Huesca"),
  ("Lilah Quinn",339,1,"Pamplona"),
  ("Melyssa Jones",412,2,"Pamplona"),
  ("Tyrone Franks",350,2,"Algeciras"),
  ("Joseph Osborn",272,2,"Santander"),
  ("Hadley Gutierrez",234,1,"Zaragoza"),
  ("Jared Hatfield",40,2,"Zaragoza");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Dominic Merritt",41,2,"Cádiz"),
  ("Jana Farmer",92,2,"Pamplona"),
  ("Benjamin Herrera",364,1,"Donosti"),
  ("Julian Mcconnell",271,2,"San Cristóbal de la Laguna"),
  ("Ima Velazquez",178,2,"Teruel"),
  ("Neve Dickson",75,1,"Badajoz"),
  ("Herman Daugherty",159,1,"Palma de Mallorca"),
  ("Shelly Nguyen",161,1,"Melilla"),
  ("Doris Christensen",152,1,"Cáceres"),
  ("Jermaine Barker",376,1,"Santander");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Shannon Pittman",312,1,"Zaragoza"),
  ("Yolanda Weaver",105,2,"Telde"),
  ("Tanek Mills",172,1,"Alcalá de Henares"),
  ("Laith Sellers",210,2,"Sabadell"),
  ("Geoffrey Crosby",45,2,"Huesca"),
  ("Tiger Bowman",35,1,"Torrevieja"),
  ("Ezekiel Simmons",281,1,"Guadalajara"),
  ("Jenna Lancaster",102,2,"Albacete"),
  ("Elijah Hardin",224,1,"Donosti"),
  ("Amethyst White",123,2,"Guadalajara"),
  ("Minerva Duke",150,1,"Alacant"),
  ("Phillip Cortez",345,1,"Palma de Mallorca"),
  ("Bevis Dillard",269,2,"Valéncia"),
  ("Vivien Stokes",62,1,"Guadalajara"),
  ("Noble Farmer",448,1,"Murcia"),
  ("Zachary Baldwin",143,2,"Ceuta"),
  ("Arthur Hamilton",61,1,"Pamplona"),
  ("Callum Stevens",95,1,"Oviedo"),
  ("Paloma Powell",175,1,"Ceuta"),
  ("Cedric Fernandez",364,2,"Ourense");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Jonas Marshall",435,1,"Oviedo"),
  ("Malik Gutierrez",245,1,"Cáceres"),
  ("Autumn Barton",152,1,"Torrevieja"),
  ("Stella Hernandez",159,1,"Pontevedra"),
  ("Yael Barrera",363,1,"Alcobendas"),
  ("Darius Orr",237,2,"Zaragoza"),
  ("Kareem Reed",100,1,"Badajoz"),
  ("Joshua Cook",95,1,"Gijón"),
  ("Desirae Mills",141,1,"Toledo"),
  ("Kiayada Dyer",341,1,"Logroño"),
  ("Lois Langley",343,2,"Oviedo"),
  ("Sybill Mcguire",229,1,"Pamplona"),
  ("Justin Robbins",379,2,"Oviedo"),
  ("Carter Combs",437,2,"Gasteiz"),
  ("Chester Downs",364,2,"Santa Cruz de Tenerife"),
  ("Nayda Sherman",242,2,"Palma de Mallorca"),
  ("Rhiannon Black",101,2,"Zaragoza"),
  ("Felix Bridges",427,2,"Almería"),
  ("Naomi Rice",250,1,"Cartagena"),
  ("Melinda Williamson",381,1,"Lugo");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Vincent Patterson",382,2,"Bilbo"),
  ("Gage Key",107,1,"Oviedo"),
  ("Colt Buckley",238,2,"Cuenca"),
  ("Lionel Patton",370,1,"Toledo"),
  ("Hayes Clark",203,1,"Vigo"),
  ("Angelica Hoffman",40,1,"Zamora"),
  ("Chase Solis",80,2,"Córdoba"),
  ("Daryl Lopez",169,1,"Santa Cruz de Tenerife"),
  ("Hedy Gomez",53,2,"Pamplona"),
  ("Fay Burgess",243,1,"Castelló");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Rigel Osborn",393,1,"Málaga"),
  ("Eagan Graham",346,1,"Palma de Mallorca"),
  ("Cyrus Chavez",294,1,"Palma de Mallorca"),
  ("Keith Castillo",266,2,"Pamplona"),
  ("Cailin Ingram",178,2,"Palma de Mallorca"),
  ("Colton Keith",321,1,"Torrevieja"),
  ("Melvin Vaughan",195,1,"Logroño"),
  ("Kaye Sandoval",428,1,"Ávila"),
  ("Bruno Gilbert",274,1,"San Cristóbal de la Laguna"),
  ("Nina Mullen",231,1,"Santander"),
  ("Latifah Greene",316,2,"Burgos"),
  ("Igor Wong",104,2,"Dos Hermanas"),
  ("Zephr Williams",359,1,"Pamplona"),
  ("Reed Stokes",102,2,"Teruel"),
  ("Fletcher Lynch",339,1,"Cáceres"),
  ("India Harrell",314,1,"Baracaldo"),
  ("Jameson Guerra",68,2,"Lugo"),
  ("Hyacinth Craig",138,1,"Marbella"),
  ("Raja Tran",317,2,"Sevilla"),
  ("Amelia Battle",432,2,"Ceuta");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Jasper Drake",427,1,"Marbella"),
  ("Orla Chambers",213,1,"Palma de Mallorca"),
  ("Orla Sloan",136,2,"Madrid"),
  ("Christine Lara",44,1,"León"),
  ("Mona Dennis",316,1,"Vigo"),
  ("Xandra Fields",87,1,"Alcalá de Henares"),
  ("Denton Wyatt",338,1,"Palma de Mallorca"),
  ("Chaney Brooks",342,2,"Salamanca"),
  ("Lionel Crawford",250,1,"Castelló"),
  ("Margaret Potter",341,1,"Melilla"),
  ("Rhona Lindsay",109,2,"Gijón"),
  ("Barry Petersen",305,2,"Alcalá de Henares"),
  ("Xavier Mercer",44,1,"Elx"),
  ("Jordan Holden",149,2,"Alacant"),
  ("Jacqueline Sharpe",425,2,"Huesca"),
  ("Vivien Herman",356,1,"Sabadell"),
  ("Malachi Bridges",315,2,"Albacete"),
  ("Reese Roman",363,2,"Oviedo"),
  ("Laurel Lowery",270,2,"Madrid"),
  ("Leo Bond",145,1,"Málaga");
INSERT INTO `peliculas_marcadiz` (`titulo`,`duracion`,`clasificacion`,`sinopsis`)
VALUES
  ("Flynn Barrera",330,2,"Oviedo"),
  ("Charles Noel",320,2,"Murcia"),
  ("Ryan Moreno",403,2,"Baracaldo"),
  ("Palmer Mcdaniel",268,1,"Oviedo"),
  ("Derek Cobb",199,1,"Pamplona"),
  ("Winter Greene",158,1,"Reus"),
  ("Russell Bright",79,2,"Murcia"),
  ("Chastity Lester",253,1,"Gijón"),
  ("Hunter Lopez",220,2,"Alcorcón"),
  ("Cassady Britt",354,2,"Elx");
